kind = "web"
previewPath = "/"
title = "УльтраКаркас"
version = "1.0.0"
id = "artifacts/ultrakarkas"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21512

[services.development]
run = "pnpm --filter @workspace/ultrakarkas run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ultrakarkas", "run", "build" ]
publicDir = "artifacts/ultrakarkas/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21512"
BASE_PATH = "/"
